In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np

from msr.utils import ordered_dict_to_dict
from msr.data.raw.mimic import load_mimic_raw_data, FS
from msr.data.measurements import MimicMeasurement
from msr.signals.representation_extractor import PeriodicRepresentationExtractor

ModuleNotFoundError: No module named 'msr.data.representation'

In [2]:
data = load_mimic_raw_data("val").numpy()
print(data.shape)

idx = 0
sample = data[idx].T
ppg, ecg = sample
print(sample.shape)

measurement = MimicMeasurement(ppg, ecg, FS)

beats_params = dict(source_channel="ecg")
windows_params = dict(win_len_s=20, step_s=18)

measurement.set_beats(**beats_params)
measurement.set_windows(**windows_params)
measurement.set_agg_beat()

(3832, 30000, 2)
(2, 30000)


/home/shate/.cache/pypoetry/virtualenvs/msr-xbuxOujG-py3.8/lib/python3.8/site-packages/neurokit2/epochs/epochs_create.py:205: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for colname, column in epochs[i].select_dtypes(include=["object"]).iteritems():
/home/shate/.cache/pypoetry/virtualenvs/msr-xbuxOujG-py3.8/lib/python3.8/site-packages/neurokit2/epochs/epochs_create.py:205: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for colname, column in epochs[i].select_dtypes(include=["object"]).iteritems():


---
# **Whole Signal**

## Waveforms

In [3]:
feats = measurement.get_whole_signal_waveforms(return_arr=True)
feats.shape

(30000, 2)

In [4]:
feats = measurement.get_whole_signal_waveforms(return_arr=False)
ordered_dict_to_dict(feats)

{'ppg': array([0.3773216 , 0.3773216 , 0.3773216 , ..., 0.59237537, 0.57282502,
        0.55229717]),
 'ecg': array([-1.61875, -1.61875, -1.6125 , ..., -1.125  , -1.15   , -0.74375])}

## Features

In [5]:
feats = measurement.get_whole_signal_features(return_arr=True)
feats.shape

(82,)

In [6]:
feats = measurement.get_whole_signal_features(return_arr=False)
ordered_dict_to_dict(feats)

{'ppg': {'PLETH_basic_features__mean': 0.4366739980449657,
  'PLETH_basic_features__std': 0.07136930045415507,
  'PLETH_basic_features__median': 0.4115347018572825,
  'PLETH_basic_features__skewness': 1.5176574405742043,
  'PLETH_basic_features__kurtosis': 1.8117975118197318,
  'PLETH_agg_beat_features__PLETH_agg_beat_basic_features__mean': 0.4476551792467023,
  'PLETH_agg_beat_features__PLETH_agg_beat_basic_features__std': 0.05285046802072915,
  'PLETH_agg_beat_features__PLETH_agg_beat_basic_features__median': 0.4320897548808988,
  'PLETH_agg_beat_features__PLETH_agg_beat_basic_features__skewness': 0.9766070125067736,
  'PLETH_agg_beat_features__PLETH_agg_beat_basic_features__kurtosis': -0.2930281488208841,
  'PLETH_agg_beat_features__PLETH_agg_beat_crit_points__systolic_peak_loc': 28,
  'PLETH_agg_beat_features__PLETH_agg_beat_crit_points__systolic_peak_time': 0.18406079999999989,
  'PLETH_agg_beat_features__PLETH_agg_beat_crit_points__systolic_peak_val': 0.5636847130042533,
  'PLETH

---
# **Windows**

## Waveforms

In [7]:
feats = measurement.get_windows_waveforms(return_arr=True)
feats.shape

(13, 2500, 2)

In [8]:
feats = measurement.get_windows_waveforms(return_arr=False)
ordered_dict_to_dict(feats)

{'ppg': OrderedDict([('window_0',
               array([0.3773216 , 0.3773216 , 0.3773216 , ..., 0.4056696 , 0.40371457,
                      0.40078201])),
              ('window_1',
               array([0.40762463, 0.39589443, 0.38709677, ..., 0.40273705, 0.40957967,
                      0.41642229])),
              ('window_2',
               array([0.39393939, 0.39491691, 0.39491691, ..., 0.37829912, 0.38416422,
                      0.39100684])),
              ('window_3',
               array([0.36070381, 0.36070381, 0.36265885, ..., 0.41446725, 0.41251222,
                      0.4115347 ])),
              ('window_4',
               array([0.45356794, 0.4398827 , 0.42815249, ..., 0.39296188, 0.40371457,
                      0.41837732])),
              ('window_5',
               array([0.38905181, 0.39393939, 0.40175953, ..., 0.50048876, 0.52394917,
                      0.54643206])),
              ('window_6',
               array([0.40273705, 0.3998045 , 0.39687195, ..

## Features

In [9]:
feats = measurement.get_windows_features(return_arr=True)
feats.shape

(13, 81)

In [10]:
feats = measurement.get_windows_features(return_arr=False)
ordered_dict_to_dict(feats)

{'ppg': {'window_0': {'PLETH_basic_features__mean': 0.43872414467253174,
   'PLETH_basic_features__std': 0.07129705886689694,
   'PLETH_basic_features__median': 0.4115347018572825,
   'PLETH_basic_features__skewness': 1.5305896382202298,
   'PLETH_basic_features__kurtosis': 1.6400368422724174,
   'PLETH_agg_beat_features__PLETH_agg_beat_basic_features__mean': 0.45017894607971454,
   'PLETH_agg_beat_features__PLETH_agg_beat_basic_features__std': 0.05083886066079673,
   'PLETH_agg_beat_features__PLETH_agg_beat_basic_features__median': 0.43324060421606325,
   'PLETH_agg_beat_features__PLETH_agg_beat_basic_features__skewness': 1.027221743353449,
   'PLETH_agg_beat_features__PLETH_agg_beat_basic_features__kurtosis': -0.29204807043864456,
   'PLETH_agg_beat_features__PLETH_agg_beat_crit_points__systolic_peak_loc': 28,
   'PLETH_agg_beat_features__PLETH_agg_beat_crit_points__systolic_peak_time': 0.1839684000000001,
   'PLETH_agg_beat_features__PLETH_agg_beat_crit_points__systolic_peak_val': 0

---
# **Beats**

## Waveforms

In [11]:
feats = measurement.get_beats_waveforms(return_arr=True)
feats.shape

(299, 100, 2)

In [12]:
feats = measurement.get_beats_waveforms(return_arr=False)
ordered_dict_to_dict(feats)

{'ppg': OrderedDict([('beat_0',
               array([0.38807429, 0.38807429, 0.38807429, 0.38807429, 0.38807429,
                      0.38808847, 0.38893476, 0.39104417, 0.39447653, 0.39914434,
                      0.40561186, 0.41571383, 0.42829594, 0.4442191 , 0.46250556,
                      0.4827036 , 0.50477395, 0.52810997, 0.55142769, 0.57430517,
                      0.59560486, 0.61512313, 0.63326813, 0.64889026, 0.65964413,
                      0.66654555, 0.67151067, 0.67470761, 0.67546226, 0.67344465,
                      0.66886284, 0.66195775, 0.65315145, 0.64235522, 0.62950736,
                      0.61610097, 0.60147575, 0.58576425, 0.56978881, 0.55461383,
                      0.54022161, 0.52525624, 0.50949674, 0.49363699, 0.478469  ,
                      0.46316178, 0.44929806, 0.43605335, 0.42431922, 0.41422573,
                      0.40469208, 0.39644405, 0.39026931, 0.38557712, 0.38217641,
                      0.38010802, 0.37928577, 0.37927664, 0.380600

## Features

In [13]:
feats = measurement.get_beats_features(return_arr=True)
feats.shape

/home/shate/Desktop/praca_magisterska/medical_signal_representation/msr/signals/utils.py:69: RuntimeWarning: invalid value encountered in double_scalars
  return (sig[end] - sig[start]) / (t[end] - t[start])
/home/shate/Desktop/praca_magisterska/medical_signal_representation/msr/signals/utils.py:69: RuntimeWarning: invalid value encountered in double_scalars
  return (sig[end] - sig[start]) / (t[end] - t[start])
/home/shate/Desktop/praca_magisterska/medical_signal_representation/msr/signals/utils.py:69: RuntimeWarning: invalid value encountered in double_scalars
  return (sig[end] - sig[start]) / (t[end] - t[start])


(299, 66)

In [14]:
feats = measurement.get_beats_features(return_arr=False)
ordered_dict_to_dict(feats)

/home/shate/Desktop/praca_magisterska/medical_signal_representation/msr/signals/utils.py:69: RuntimeWarning: invalid value encountered in double_scalars
  return (sig[end] - sig[start]) / (t[end] - t[start])
/home/shate/Desktop/praca_magisterska/medical_signal_representation/msr/signals/utils.py:69: RuntimeWarning: invalid value encountered in double_scalars
  return (sig[end] - sig[start]) / (t[end] - t[start])
/home/shate/Desktop/praca_magisterska/medical_signal_representation/msr/signals/utils.py:69: RuntimeWarning: invalid value encountered in double_scalars
  return (sig[end] - sig[start]) / (t[end] - t[start])


{'ppg': {'beat_0': {'beat_0_resampleWithInterp(100)_basic_features__mean': 0.4762388779422793,
   'beat_0_resampleWithInterp(100)_basic_features__std': 0.08996216989601277,
   'beat_0_resampleWithInterp(100)_basic_features__median': 0.4496005308214105,
   'beat_0_resampleWithInterp(100)_basic_features__skewness': 1.0170661389211229,
   'beat_0_resampleWithInterp(100)_basic_features__kurtosis': -0.22958336870339835,
   'beat_0_resampleWithInterp(100)_crit_points__systolic_peak_loc': 28,
   'beat_0_resampleWithInterp(100)_crit_points__systolic_peak_time': 0.18368,
   'beat_0_resampleWithInterp(100)_crit_points__systolic_peak_val': 0.675462256109482,
   'beat_0_resampleWithInterp(100)_sppg_features__duration': 0.656,
   'beat_0_resampleWithInterp(100)_sppg_features__systolic_peak_val': 0.675462256109482,
   'beat_0_resampleWithInterp(100)_sppg_features__systolic_peak_time': 0.18368,
   'beat_0_resampleWithInterp(100)_sppg_features__systolic_onset_slope': 1.5646121777514383,
   'beat_0_res

---
# **Aggregated beat**

## Waveforms

In [15]:
feats = measurement.get_agg_beat_waveforms(return_arr=True)
feats.shape

(100, 2)

In [16]:
feats = measurement.get_agg_beat_waveforms(return_arr=False)
ordered_dict_to_dict(feats)

{'ppg': array([0.39630578, 0.39779235, 0.39944728, 0.40121364, 0.40313995,
        0.40534605, 0.40782495, 0.41062214, 0.41383369, 0.41766189,
        0.42229524, 0.42784915, 0.43448963, 0.44210183, 0.45078322,
        0.46040183, 0.47071282, 0.4815121 , 0.49277256, 0.50413763,
        0.51507924, 0.52540255, 0.5349039 , 0.54333969, 0.55044549,
        0.55615249, 0.56024169, 0.56270951, 0.56368471, 0.56318124,
        0.56120708, 0.55782225, 0.55313704, 0.54721936, 0.54031549,
        0.53263937, 0.52438688, 0.51560494, 0.50635408, 0.49679745,
        0.48708012, 0.47731793, 0.46757557, 0.45792641, 0.44856655,
        0.43962195, 0.43116272, 0.42324466, 0.41599032, 0.40937662,
        0.40348495, 0.39839269, 0.39412735, 0.39068391, 0.38803588,
        0.38626012, 0.38536913, 0.38530462, 0.3859837 , 0.3873909 ,
        0.38952931, 0.39222765, 0.395453  , 0.39907893, 0.40297106,
        0.40708834, 0.41125014, 0.41534946, 0.41936856, 0.42324613,
        0.42687882, 0.43023865, 0.4332822

## Features

In [17]:
feats = measurement.get_agg_beat_features(return_arr=True)
feats.shape

(66,)

In [18]:
feats = measurement.get_agg_beat_features(return_arr=False)
ordered_dict_to_dict(feats)

{'ppg': {'PLETH_agg_beat_basic_features__mean': 0.4476551792467023,
  'PLETH_agg_beat_basic_features__std': 0.05285046802072915,
  'PLETH_agg_beat_basic_features__median': 0.4320897548808988,
  'PLETH_agg_beat_basic_features__skewness': 0.9766070125067736,
  'PLETH_agg_beat_basic_features__kurtosis': -0.2930281488208841,
  'PLETH_agg_beat_crit_points__systolic_peak_loc': 28,
  'PLETH_agg_beat_crit_points__systolic_peak_time': 0.18406079999999989,
  'PLETH_agg_beat_crit_points__systolic_peak_val': 0.5636847130042533,
  'PLETH_agg_beat_sppg_features__duration': 0.6573599999999996,
  'PLETH_agg_beat_sppg_features__systolic_peak_val': 0.5636847130042533,
  'PLETH_agg_beat_sppg_features__systolic_peak_time': 0.18406079999999989,
  'PLETH_agg_beat_sppg_features__systolic_onset_slope': 0.9093676192824903,
  'PLETH_agg_beat_sppg_features__systolic_offset_slope': 0.3345103348888811,
  'PLETH_agg_beat_sppg_features__energy': 0.20318833147640725,
  'PLETH_agg_beat_sppg_features__before_systolic_a

---
# **RepresentationExtractor**

In [19]:
rep_extractor = PeriodicRepresentationExtractor(measurement)

rep_extractor.set_beats(**beats_params)
rep_extractor.set_windows(**windows_params)
rep_extractor.set_agg_beat()

reps = rep_extractor.get_representations(representation_types="all", return_arr=True)

for name, rep in reps.items():
    print(name, rep.shape)

/home/shate/.cache/pypoetry/virtualenvs/msr-xbuxOujG-py3.8/lib/python3.8/site-packages/neurokit2/epochs/epochs_create.py:205: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for colname, column in epochs[i].select_dtypes(include=["object"]).iteritems():
/home/shate/.cache/pypoetry/virtualenvs/msr-xbuxOujG-py3.8/lib/python3.8/site-packages/neurokit2/epochs/epochs_create.py:205: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for colname, column in epochs[i].select_dtypes(include=["object"]).iteritems():
/home/shate/Desktop/praca_magisterska/medical_signal_representation/msr/signals/utils.py:69: RuntimeWarning: invalid value encountered in double_scalars
  return (sig[end] - sig[start]) / (t[end] - t[start])
/home/shate/Desktop/praca_magisterska/medical_signal_representation/msr/signals/utils.py:69: RuntimeWarning: invalid value encountered in double_scalars
  return (sig[end] - si

whole_signal_waveforms (30000, 2)
whole_signal_features (82,)
windows_waveforms (13, 2500, 2)
windows_features (13, 81)
beats_waveforms (299, 100, 2)
beats_features (299, 66)
agg_beat_waveforms (100, 2)
agg_beat_features (66,)
